//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Login()
        {
            this.Tbl_From = new HashSet<Tbl_From>();
        }
    
        public int Login_ID { get; set; }
        public System.Guid Login_Guid { get; set; }
        public int Login_RoleID { get; set; }
        public string Login_Email { get; set; }
        public string Login_Name { get; set; }
        public string Login_Family { get; set; }
        public string Login_Hash { get; set; }
        public string Login_Salt { get; set; }
        public System.DateTime Login_CreateDate { get; set; }
        public System.DateTime Login_Modify { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_From> Tbl_From { get; set; }
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
