//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FormStep
    {
        public int FS_ID { get; set; }
        public System.Guid FS_Guid { get; set; }
        public string FS_Name { get; set; }
        public int FS_Order { get; set; }
        public string FS_Display { get; set; }
        public int FS_FormID { get; set; }
    
        public virtual Tbl_From Tbl_From { get; set; }
    }
}
